approved = [
  "apache-2.0",
  "bsd-2-clause",
  "bsd-3-clause",
  "isc",
  "mit",
  "mit-0",
]

ignored = [
  "google.golang.org/protobuf", # Unsupported VCS, bsd-3-clause
]

[header]
ignoreFiles = ["zz_generated.*.go", "generated.go", "cache.go"]
authors = ["Axoflow"]
template = """// Copyright © :YEAR: :AUTHOR:
// All rights reserved."""
