approved = [
  "apache-2.0",
  "bsd-2-clause",
  "bsd-3-clause",
  "isc",
  "mit",
  "mit-0",
]

ignored = [
  "github.com/gogo/protobuf", # Custom license
  "google.golang.org/protobuf", # Unsupported VCS, bsd-3-clause
  "sigs.k8s.io/yaml", # MIT + Custom license
  "github.com/hashicorp/go-envparse", # MPL-2.0, but we should get rid of it when replacing node_exporter
  "emperror.dev/errors", # MIT
  "github.com/soundcloud/go-runit", # repository removed, indirect, MIT
]

[header]
ignoreFiles = ["zz_generated.*.go", "generated.go", "cache.go"]
authors = ["Axoflow"]
template = """// Copyright © :YEAR: :AUTHOR:
// All rights reserved."""
