name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: '.go-version'

      - name: Cache licenses
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684 # v4.2.3
        with:
          key: licensei-cache-${{ hashFiles('go.sum') }}
          path: ".licensei.cache"
          restore-keys: licensei-cache

      - name: Ensure licensei cache
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make .licensei.cache

      - name: Run license check
        run: make check-license

  test:
    name: Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: '.go-version'

      - name: Run tests
        run: make test

  lint:
    name: Go lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: '.go-version'

      - name: Lint
        run: make lint
        env:
          LINTER_FLAGS: '--timeout 5m'

  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yaml
    with:
      publish: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
