name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: '.go-version'

      - name: Cache licenses
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          key: licensei-cache-${{ hashFiles('go.sum') }}
          path: ".licensei.cache"
          restore-keys: licensei-cache

      - name: Ensure licensei cache
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make .licensei.cache

      - name: Run license check
        run: make check-license

  test:
    name: Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: '.go-version'

      - name: Run tests
        run: make test

  lint:
    name: Go lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Set up Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e # v7.0.0
        with:
          go-version-file: '.go-version'

      - name: Lint
        run: make lint
        env:
          LINTER_FLAGS: '--timeout 5m'

  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yaml
    with:
      publish: ${{ github.event_name == 'push' }}
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
