name: Go basic checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license-check:
    name: License check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: '.go-version'

      - name: Cache licenses
        uses: actions/cache@1bd1e32a3bdc45362d1e726936510720a7c30a57 # v4.2.0
        with:
          key: licensei-cache-${{ hashFiles('go.sum') }}
          path: ".licensei.cache"
          restore-keys: licensei-cache

      - name: Ensure licensei cache
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: make .licensei.cache

      - name: Run license check
        run: make check-license

  run-test:
    name: Go tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: '.go-version'

      - name: Run tests
        run: make test

  run-lint:
    name: Go lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: '.go-version'

      - name: Lint
        run: make lint
        env:
          LINTER_FLAGS: '--timeout 5m'
