name: Pre-release
# build and tag image for semver pre-releases (like 1.2.3-dev)

on:
  push:
    tags: ["[0-9]+.[0-9]+.[0-9]+-*"]

permissions:
  contents: read

jobs:
  artifacts:
    name: Artifacts
    uses: ./.github/workflows/artifacts.yaml
    with:
      publish: true
      release: false
    permissions:
      contents: read
      packages: write
      id-token: write
      security-events: write
